language: cpp

matrix:
  include:
    - os: windows

install:
  # Enable running local PowerShell scripts
  - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'

script:
  - ./example_windows_script.bat