language: cpp

matrix:
  include:
    - os: windows

install:
  # Enable running local PowerShell scripts
  - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'

script:
  - find ~/.bin
  - find ~/bin
  - env
  - make --version
  - example_windows_script.bat
  - PowerShell -Command 'Get-Location'
  - PowerShell -File 'example_powershell_script.ps1'