language: cpp
sudo: required

dist: trusty

cache:
  directories:
  - mozilla-central-52
  - patches
  - mozilla-build
  - build/mozilla-central-52

addons:
  homebrew:
    packages:
    - node
    - yasm
    - mercurial
    - cmake
    - gawk
    - ccache
    - autoconf@2.13
  apt:
    packages:
    - nodejs
    - yasm
    - autoconf2.13
    - libgtk2.0-dev
    - libgtk-3-dev
    - libgconf2-dev
    - libasound2-dev
    - libpulse-dev
    - libxt-dev
    - libxext-dev
    - libxcb-shm0-dev
    - libx11-xcb-dev
    - mesa-common-dev
    - libgl1-mesa-dev

jobs:
 include:
 - os: osx
   script: ./build.sh
 - os: linux
   script: ./build.sh
 - os: windows
   filter_secrets: false
   script: travis_wait 30 ./windows-toolkit.sh

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.deploy.sh