language: cpp

matrix:
  include:
    - os: windows

install:
  # Enable running local PowerShell scripts
  - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'

script:
  - find ~/.bin
  - find ~/bin
  - env
  - git config -l
  - make --version
  - PowerShell -Command 'Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table -AutoSize'
  - PowerShell -Command 'Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table -AutoSize'
  - example_windows_script.bat
  - PowerShell -Command 'Get-Location'
  - PowerShell -File 'example_powershell_script.ps1'