language: cpp
sudo: required

dist: trusty
osx_image: xcode8

os:
  - linux
  - osx
  - windows

env:
  - ARCH="x86_64"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Updating Homebrew...";
      brew update;
      brew tap homebrew/versions;
      sudo chown -R $(whoami) /usr/local;
      brew unlink node; brew unlink mercurial; brew unlink cmake; brew unlink autoconf;
      brew install node yasm mercurial cmake gawk ccache autoconf@2.13;
      brew link --overwrite cmake;
      brew link --overwrite mercurial;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      curl -sL https://deb.nodesource.com/setup_7.x | sudo bash -;
      sudo apt-get install nodejs yasm autoconf2.13;
      sudo apt-get install libgtk2.0-dev libgtk-3-dev libgconf2-dev;
      sudo apt-get install libasound2-dev libpulse-dev;
      sudo apt-get install libxt-dev libxext-dev libxcb-shm0-dev libx11-xcb-dev;
      sudo apt-get install mesa-common-dev libgl1-mesa-dev;
    fi

script:
  - ./build.sh --arch ${ARCH}

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.deploy.sh