language: cpp
sudo: required

dist: trusty

cache:
  directories:
  - patches
  - mozilla-build
  - build/mozilla-central-52

addons:
  homebrew:
    packages:
    - node
    - yasm
    - mercurial
    - cmake
    - awk
    - ccache
    - autoconf@2.13
  apt:
    packages:
    - yasm
    - autoconf2.13
    - libgtk2.0-dev
    - libgtk-3-dev
    - libgconf2-dev
    - libasound2-dev
    - libpulse-dev
    - libxt-dev
    - libxext-dev
    - libxcb-shm0-dev
    - libx11-xcb-dev
    - mesa-common-dev
    - libgl1-mesa-dev

jobs:
 include:
# - os: osx
#   cache:
#     directories:
#       - mozilla-central-52
#   script: ./build.sh
# - os: linux
#   cache:
#     directories:
#       - mozilla-central-52
#   before_install:
#    - curl -sL https://deb.nodesource.com/setup_7.x | sudo bash -
#   script: ./build.sh
 - os: windows
   filter_secrets: false
   before_install:
    - choco install nodejs && export PATH=/c/Program\ Files/nodejs/npm:$PATH && node --version
   install:
    - npm install --global windows-build-tools --vs2015
    - choco install vcpython27
   script: ./windows-toolkit.sh

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.deploy.sh
