language: cpp
sudo: required

dist: trusty
#osx_image: xcode10

os:
  - osx
  - windows

env:
  - ARCH="x86_64"

cache:
  directories:
  - mozilla-central-52
  - patches
  - mozilla-build
  - build/mozilla-central-52

addons:
  homebrew:
    packages:
    - node
    - yasm
    - mercurial
    - cmake
    - gawk
    - ccache
    - autoconf@2.13

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ./build.sh --arch ${ARCH};
    fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      PowerShell -Command 'Write-Output "Started build (OUTPUT)"' -Verbose;
      PowerShell -Command 'Write-Host "Started build (HOST)"' -Verbose;
      PowerShell Get-Process;
      PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned' -Verbose;
      PowerShell -File 'windows-toolkit.ps1' -Verbose;
    fi

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.deploy.sh

jobs:
 include:
 - os: linux
   before_install:
    - sudo apt-get update;
    - curl -sL https://deb.nodesource.com/setup_7.x | sudo bash -;
    - sudo apt-get install nodejs yasm autoconf2.13;
    - sudo apt-get install libgtk2.0-dev libgtk-3-dev libgconf2-dev;
    - sudo apt-get install libasound2-dev libpulse-dev;
    - sudo apt-get install libxt-dev libxext-dev libxcb-shm0-dev libx11-xcb-dev;
    - sudo apt-get install mesa-common-dev libgl1-mesa-dev;
   script:
    - ./build.sh --arch ${ARCH};
 - os: windows
   script:
    - powershell 'Write-Output "Started build (OUTPUT)"'
	- powershell 'windows-toolkit.ps1'